version: "3"

services:
  web:
    image: esc20936/python-ml-api:latest  # Replace this with your own Docker Hub image
    container_name: web
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      # - letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
