name: Retrain Model

on:
  workflow_dispatch:
    # Allows manually triggering the workflow from the Actions tab
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight (optional)

jobs:
  retrain-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version that matches your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes you have a requirements.txt file
        pip install joblib  # Install additional packages if required

    - name: Run retrain.py
      run: cd models && python retrain.py  # Path to your retrain.py script
